### ISSUE TITLE
Rethink how to help people stuck on a given step

### ISSUE THREAD

**Issue by bookercodes** [scrimba/discord-bot#24]
If someone gets stuck on a step, the bot jumps in an explains, "If you are having trouble, you can message Alex from Scrimba" (that's me 🙋🏻!) 

I feel bad because I can't respond to eveyone in a timely manner (it becomes too distracting) and sometimes I miss messages. 

I was offline for 10 days and the world kept spinning. Maybe we could remove the offer to message someone from Scrimba? @codeluggage, now you have the reigns I don't think it makes sense that the bot mentions me anymore.

Some observations,
- Of the small number of people who get stuck, 90% of them get stuck on the step that links their Discord and Scrimba account. In my experience, this normally happens because they are logged into a different Discord account in their browser than in the app. Instead of offering to message someone from the team, I think we can anticipate this likely issue and offer help in the form of documentation 
- A small number of people want support with a billing issue and decide to message me directly as soon it occurs to them that's an option. They should really be emailing help@scrimba.com. We could consult Roku about routing **all** issues to to help@scrimba.com where they can be triaged 
- I have not yet experienced someone fail to complete the onboarding because of a bug with the bot, although I am sure it could happen. There are a few rare edge-cases in the event that the server is restarted or something like that. By the way, if that ever happens leaving and rejoining the server will always fix the problem

**Comment by codeluggage** [comment]
Closed with #27
