### ISSUE TITLE
Store karma in main DB instead of discord-bot only 

### ISSUE THREAD

**Issue by Pistus** [scrimba/discord-bot#26]
To allow us to show the user that they have new Karma, if they are eligable for badges, hoodies, etc. we need to store the karma in a way that the site can access it and that would be in the main db. So the question is if the discord-bot should have direct access to the db via a connection or through an api. 

Direct connection - much more flexible - allows both fetching and storing data easily; but a breach of the bot or bot server gives access to the db. Can be somewhat limited with a postgres user with restricted access.

API - need to setup api's for all actions to be done, but allows other systems to use the same api's. The Amazon approach would be an API.

**Comment by codeluggage** [comment]
Closed with #36
