### ISSUE TITLE
some of the onboarding channels show up for everyone

### ISSUE THREAD

**Issue by sriyansreddyy** [scrimba/discord-bot#43]
Hey there, sometimes few of the onboarding channels are visible to others. An example which occurred today
![image](https://user-images.githubusercontent.com/80452443/141988543-09516a52-59b8-47fd-bc63-6f96342f8a92.png)

**Comment by sriyansreddyy** [comment]
FYI, this happened twice a while ago

**Comment by Pistus** [comment]
Thanks for reporting @sriyansreddyy  - we have re-written the bot to the image language and the permissions seems to have been set wrong in this process. Will have the team take a look.

**Comment by codeluggage** [comment]
Closed with #47
