### ISSUE TITLE
Onboarding process halts for certain users without any error messages

### ISSUE THREAD

**Issue by Pistus** [scrimba/discord-bot#46]
So at the moment anyone can see the onboarding channels, and as part of that I can see that several people are answering the bot with their first name, but the process does not continue (as far as I can see). That said the users have the peep role! Maybe someone in the team set it for them (I have asked).

First thoughts:
1. The bot does not receive the message properly (network issue?)
2. I do not see the response as the permissions of the channel is changed - aka. the initial permissions is wrong?

Example 1:
<img width="1395" alt="Screenshot 2021-11-16 at 17 07 56" src="https://user-images.githubusercontent.com/1829960/142022134-b052fb77-63d8-43e4-8ee3-85b50fe1fec7.png">

Example 2:
<img width="710" alt="Screenshot 2021-11-16 at 17 07 44" src="https://user-images.githubusercontent.com/1829960/142022178-7b9572ed-f817-4f1e-b95b-5f26f3b2afe4.png">

<img width="1395" alt="Screenshot 2021-11-16 at 17 07 51" src="https://user-images.githubusercontent.com/1829960/142022173-0a93f25c-5b07-48fb-9d37-65dc586c563c.png">

**Comment by Pistus** [comment]
Nobody seems to have added the role's so that means that some of the users that seem to have been stuck actually got through the onboarding.

**Comment by codeluggage** [comment]
Closed with #47
